Test/menu
noahlissner/js-inl2-webbshop pull request #23
Opened 2021-12-13 14:57 UTC by elilyx10

Hello team!

Here are the test for navigating the menu. 

Please review!

Thanks!

2021-12-13 15:58 UTC, dennislundgren requested changes
cy.visit("http://localhost:1234"); // Uteslut s:et ur länken.
cy.get(".list__item").contains("About").click(); // Syntax för att hitta och klicka på menyval.

Samla allt i en menu.spec.ts-fil där endast en describe finns med.

Kika igenom våra tester som referens!

2021-12-13 16:00 UTC, elilyx10 commented
Tack!

2021-12-14 08:43 UTC, dennislundgren commented on cypress/integration/menu.spec.ts.ts
> +
------>

2021-12-14 08:43 UTC, dennislundgren commented on cypress/integration/menu.spec.ts.ts
> +
----->

2021-12-14 08:43 UTC, dennislundgren commented on cypress/integration/menu.spec.ts.ts
> +
------->

2021-12-14 08:44 UTC, dennislundgren requested changes
Add cy.get("").should("",""); to the tests as these will determine its result.
See comments.

Ex.:
cy.get('header__icon-container--burger').should('have.class', 'open');

2021-12-14 08:48 UTC, dennislundgren commented on cypress/integration/menu.spec.ts.ts
> +
cy.url().should('include', '/users/1/edit') // => true

See reference document from Cypress:
https://docs.cypress.io/api/commands/url#No-Args

2021-12-15 14:18 UTC, noahlissner approved these changes

2021-12-15 14:19 UTC, merged